### ISSUE TITLE
Virtual text not always displaying

### ISSUE THREAD

**Issue by Iron-E** [nvim-lua/diagnostic-nvim#40]
From #36:

> Hmm… one thing I am noticing is that `g:diagnostic_enable_virtual_text` isn't doing anything for me right now (no virtual text is shown, only things in the sign column. Is this happening for you too?
> 
> Seems to be happening only on certain language servers. `sumneko_lua` and `bashls` are two of them, but interestingly enough `omnisharp` and `gopls` work but the diagnostics stay on screen after they should disappear.

I'll add that currently `omnisharp` is one of the more troubled language servers with `nvim_lsp`, so it's odd that it's working there.

Popups work on all servers I've tried, and so do items in the sign column.

**Comment by aktau** [comment]
For me, `gopls` has the behaviour where the diagnostics stay on screen even when they should disappear.

**Comment by Iron-E** [comment]
I can confirm that behavior as well. Are you able to test `bashls` or `sumneko_lua` to see if you get the other behaviors from the OP there too?

**Comment by aktau** [comment]
I think I can confirm that this bug is not related to virtual text, but to the diagnostics itself. I've switched from using virtual texts to popups on CursorHold (https://github.com/nvim-lua/diagnostic-nvim/issues/29) and I see the same phenomenon: 

  * I see (two) diagnostics (which are accurate) when opening the file.
  * After removing the line which provoked one diagnostic (and saving), the diagnostic still exists, now on an empty line.

Before:

![Screenshot 2020-07-07 at 11 51 12](https://user-images.githubusercontent.com/189413/86764464-584f6d00-c048-11ea-907a-c8572e55d563.png)

After:

![Screenshot 2020-07-07 at 11 51 32](https://user-images.githubusercontent.com/189413/86764477-5be2f400-c048-11ea-931e-7d3b42cf835c.png)


I can confirm this happens with `efm` and `gopls` langservers. I don't have the two others requested by @Iron-E above.

**Comment by aktau** [comment]
I tried disabling `diagnostic-nvim` (commenting out `Plug` and `on_attach`) and the situation persists. So this may not be due to `diagnostic-nvim`.

At this point I'm thinking something may be wrong with `util.buf_clear_diagnostics(bufnr)` and/or `util.buf_diagnostics_save_positions(bufnr, result.diagnostics)`, though I don't know this code (at all).

Also. I did not know that vanilla nvim-lsp had signs and virtual text: https://github.com/neovim/neovim/blob/91572ddad185c2c4f6d266543d66919543c5bb2a/runtime/lua/vim/lsp/callbacks.lua#L100. As a side note it may be good to specify in the README how this plugin differs/enhances the default experience.

**Comment by aktau** [comment]
So, the only artifact that (seems to) remain after calling `vim.buf_clear_diagnostics(bufnr)` is the stuff fetched by `vim.lsp.util.show_line_diagnosticc` (https://github.com/neovim/neovim/blob/91572ddad185c2c4f6d266543d66919543c5bb2a/runtime/lua/vim/lsp/util.lua#L949) and `Prev/NextDiagnostic` (which uses everything from the location list without filtering if I'm reading this right).

```lua
  function M.get_line_diagnostics()
    local bufnr = api.nvim_get_current_buf()
    local linenr = api.nvim_win_get_cursor(0)[1] - 1

    local buffer_diagnostics = M.diagnostics_by_buf[bufnr]

    if not buffer_diagnostics then
      return {}
    end

    local diagnostics_by_line = M.diagnostics_group_by_line(buffer_diagnostics)
    return diagnostics_by_line[linenr] or {}
  end
```

**Comment by megalithic** [comment]
confirmed.. if you don't include `require'diagnostic'.on_attach()` as part of your on_attach function that you bind to your lsps, then it works (you still get the virtual text, but of course, other settings don't work at that point).

**Comment by Iron-E** [comment]
It seems that the virtual text function (`lua/diagnostic/util.lua` @ line 72) is roughly based on `vim.lsp.util.buf_diagnostics_virtual_text()`. I expected that the error was somewhere in the difference, although the `:Gblame` shows me that this repo's version hasn't been touched in several months which means the error must be elsewhere.

**Comment by megalithic** [comment]
I'll say that I noticed the "break" when i switched to the new github org of nvim-lua from @haorenW1025 's own account.

**Comment by Iron-E** [comment]
Do you remember around what commit that was? I noticed a lot of these bugs popped up about that time. I could `git bisect` if I knew.

**Comment by aktau** [comment]
Sorry, after thinking about it for a bit more it may be that my issue is not the same as the issue in this post. I never had the problem that virtual text wasn't always displayed. My problem is that it's sometimes displayed when I think it shouldn't. But after investigating I've found out that:

  1. It has nothing to do with virtual text. The diagnostics just don't go away while they should.
  2. After fixing (what I think is) a bug in `buf_clear_diagnostics` (see https://github.com/nvim-lua/diagnostic-nvim/issues/40#issuecomment-654751632). I noticed that now `gopls` was fixed (diagnostics dissapear correctly) but `efm-langserver` wasn't.
  3. Investigating `efm-langserver` shows that it tells vim about these diagnostics, but they are of zero width (see below). This is either a bug in (a) the `efm-langserver`, (b) how nvim-lsp sends `textDocument/didChange` to `efm-langserver` or (c) how nvim-lsp interprets zero-width diagnostics (perhaps they should be ignored?).

So, sorry for the noise. I'll create issues elsewhere once I've dug some more.

```
# Before deleting line 5 (it' indeed has a flaw warranting a diagnostic):
range = {
  end = {          character = 8,          line = 4        },
  start = {          character = 5,          line = 4        }
},

# After deleting line 5, making it now an empty line:
range = {
  end = {          character = 5,          line = 4        },
  start = {          character = 5,          line = 4        }
},
```

**Comment by megalithic** [comment]
@haorenW1025 any thoughts around this?

**Comment by haorenW1025** [comment]
Sorry for the responding... I was too busy this couple days. However I haven't noticed any issue on my side(mainly using sumneko_lua and clangd). I made a possible fix and please try if it solves your issues.

**Comment by Iron-E** [comment]
If I understood @aktau's findings correctly, I think that latest commit may fix his issue. Although the things I noticed [here](https://github.com/nvim-lua/diagnostic-nvim/issues/40#issuecomment-655075588) are still happening.

**Comment by aktau** [comment]
I think https://github.com/nvim-lua/diagnostic-nvim/commit/d7734f12f2c980b08c205583b7756d735222fb9f is just a partial fix, `vim.lsp.util.buf_clear_diagnostics` itself also needs to clear the Lua table that contains the diagnostics (what I mentioned in https://github.com/nvim-lua/diagnostic-nvim/issues/40#issuecomment-654751632). However, a fix for that would need to be submitted to the main neovim repository. I'll see if I can make a PR.

**Comment by haorenW1025** [comment]
@aktau Yeah the fix should be in the neovim repo, please tag me if you open a PR, thanks:)

**Comment by aktau** [comment]
Done. Also, once again I got confused as this issue (as described by @Iron-E) is likely not exactly the same thing as what I'm experiencing. Of course, fixing my bug will mean less potential confusion/causes. From the original report, I only experienced the following (highlighted):

> Hmm… one thing I am noticing is that g:diagnostic_enable_virtual_text isn't doing anything for me right now ~~(no virtual text is shown, only things in the sign column. Is this happening for you too?~~
>
> Seems to be happening only on certain language servers. sumneko_lua and bashls are two of them, but interestingly enough omnisharp and gopls work **but the diagnostics stay on screen after they should disappear**.

Let's see if the fixes make the second issue go away, and then we could deal with the first (if it can be reproduced).

**Comment by Iron-E** [comment]
I should have noted this here earlier: `omnisharp` no longer exhibits the staying-on-screen behavior for me following [this](https://github.com/OmniSharp/omnisharp-roslyn/issues/1191#issuecomment-653787100) fix. It appears that language server's error was unrelated to this issue.

**Comment by Iron-E** [comment]
Okay, so I went ahead and performed a local merge of your PR using neovim/neovim as a base (I don't use the appimage anyway). This issue has been fixed:

> interestingly enough ~~omnisharp and~~ `gopls` work but the diagnostics stay on screen after they should disappear.

However this issue still persists for me:

> no virtual text is shown, only things in the sign column

and

> Seems to be happening only on certain language servers. `sumneko_lua` and `bashls` are two of them.

[Here](https://imgur.com/a/jOfAhdb) are some screenshots to demonstrate the issue.

**Comment by megalithic** [comment]
confirmed, same behaviour; add elixirls to that list of ones not showing virtualtext, but shows the sign in signcolumn.

**Comment by el-iot** [comment]
@haorenW1025  I've made a pull-request that fixes this issue for me, check out #50.

**Comment by Iron-E** [comment]
I can confirm that #50 has fixed the issue. I will close it. Thank you!
